version: '3'

tasks:
  start:*:
    vars:
      day: "{{index .MATCH 0}}"
    cmds:
      - mkdir -p "Codyssi2024/Day{{.day}}"
      - cp "./Codyssi2024/TemplatePart.txt" "./Codyssi2024/Day{{.day}}/Part1.cs"
      - sed -i "s/X/{{.day}}/g" ./Codyssi2024/Day{{.day}}/Part1.cs
      - sed -i "s/Y/1/g" ./Codyssi2024/Day{{.day}}/Part1.cs
      - cp "./Codyssi2024/TemplatePart.txt" "./Codyssi2024/Day{{.day}}/Part2.cs"
      - sed -i "s/X/{{.day}}/g" ./Codyssi2024/Day{{.day}}/Part2.cs
      - sed -i "s/Y/2/g" ./Codyssi2024/Day{{.day}}/Part2.cs
      - cp "./Codyssi2024/TemplatePart.txt" "./Codyssi2024/Day{{.day}}/Part3.cs"
      - sed -i "s/X/{{.day}}/g" ./Codyssi2024/Day{{.day}}/Part3.cs
      - sed -i "s/Y/3/g" ./Codyssi2024/Day{{.day}}/Part3.cs
      - git add .